name: Terraform Apply - State Backend

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_BOOTSTRAP_ROLE_ARN: ${{ vars.AWS_BOOTSTRAP_ROLE_ARN }}
  AWS_TERRAFORM_ROLE: ${{ vars.AWS_TERRAFORM_ROLE }}
  TF_VAR_state_bucket_name: ${{ vars.TF_VAR_state_bucket_name }}

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ">=1.5.0"

      - name: Configure AWS Bootstrap Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ env.AWS_BOOTSTRAP_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Assume Terraform Target Role
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ env.AWS_TERRAFORM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
          role-chaining: true

      - name: Terraform Apply
        run: |
          cd terraform/environments/dev
          terraform init
          terraform apply -auto-approve
        env:
          TF_VAR_state_bucket_name: ${{ env.TF_VAR_state_bucket_name }}
          TF_VAR_region: ${{ env.AWS_REGION }}